name: Kernel & Manager Builder (Caller)

on:
  workflow_dispatch:
    inputs:
      manifest_name:
        description: 'Nama file XML di folder .github/manifest/ (tanpa .xml)'
        required: true
        type: string
        default: 'camellia'
      build_target:
        description: 'Pilih komponen yang ingin di-build'
        required: true
        type: choice
        default: 'both'
        options:
          - 'both'
          - 'kernel_only'
          - 'manager_only'
      ksu_fork:
        description: 'Pilih Fork KernelSU'
        required: true
        type: choice
        default: 'xxKSU'
        options:
          - 'xxKSU'
          - 'SUKISU'
          - 'KernelSU'
      include_susfs:
        description: 'Sertakan Patch SUSFS 4.14'
        required: true
        type: boolean
        default: true
      include_bbg:
        description: 'Sertakan Baseband-Guard (BBG)'
        required: true
        type: boolean
        default: true
      use_proton_clang:
        description: 'Gunakan Proton-Clang (True) atau AOSP Clang (False)'
        required: true
        type: boolean
        default: true

jobs:
  trigger-build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      manifest_name: ${{ inputs.manifest_name }}
      build_target: ${{ inputs.build_target }}
      ksu_fork: ${{ inputs.ksu_fork }}
      include_susfs: ${{ inputs.include_susfs }}
      include_bbg: ${{ inputs.include_bbg }}
      use_proton_clang: ${{ inputs.use_proton_clang }}
    secrets: inherit
