name: Kernel & Manager Builder (Caller)

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'What should be built?'
        required: true
        type: choice
        default: 'both'
        options:
          - 'both'
          - 'kernel_only'
          - 'manager_only'

      ksu_fork:
        description: 'Which ksu fork should be made?'
        required: true
        type: choice
        default: 'xxKSU'
        options:
          - 'xxKSU'
          - 'SUKISU'
          - 'KernelSU'

      manifest_name:
        description: 'Which kernel should be built?'
        required: true
        type: choice
        default: 'camellia'
        options:
          - 'camellia'

      include_extra_features:
        description: 'Support for additional managers & patches (SUSFS/BBG)?'
        required: true
        type: boolean
        default: true

      toolchain:
        description: 'Kernel Toolchain (official AOSP or proton-clang)'
        required: true
        type: choice
        default: 'proton-clang'
        options:
          - 'proton-clang'
          - 'aosp-clang'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      build_target: ${{ inputs.build_target }}
      ksu_fork: ${{ inputs.ksu_fork }}
      manifest_name: ${{ inputs.manifest_name }}
      include_extra_features: ${{ inputs.include_extra_features }}
      toolchain: ${{ inputs.toolchain }}
    secrets: inherit
