name: Build Kernel & Tools (Automated Pipeline)

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Pilih Target Build'
        required: true
        type: choice
        default: 'both'
        options:
          - 'both'
          - 'kernel_only'
          - 'manager_only'
      ksu_fork:
        description: 'Pilih Fork KernelSU'
        required: true
        type: choice
        default: 'xxKSU'
        options:
          - 'xxKSU'
          - 'SUKISU'
          - 'Official'
      manifest_name:
        description: 'Nama File Manifest (tanpa .xml)'
        required: true
        type: string
        default: 'camellia'
      include_extra_features:
        description: 'Sertakan SUSFS & Baseband-Guard (BBG)'
        required: true
        type: boolean
        default: true
      toolchain:
        description: 'Pilih Toolchain Clang'
        required: true
        type: choice
        default: 'proton-clang'
        options:
          - 'proton-clang'
          - 'aosp-clang'
          - 'zyc-clang'
          - 'azure-clang'
          - 'eva-gcc'

permissions:
  contents: write

jobs:
  # -------------------------------------------------------------------------
  # JOB 1: OTOMATIS MEMANGGIL WORKER KERNEL & MANAGER
  # -------------------------------------------------------------------------
  build-kernel-and-manager:
    uses: ./.github/workflows/build-kernel.yml
    with:
      build_target: ${{ inputs.build_target }}
      ksu_fork: ${{ inputs.ksu_fork }}
      manifest_name: ${{ inputs.manifest_name }}
      include_extra_features: ${{ inputs.include_extra_features }}
      toolchain: ${{ inputs.toolchain }}
    secrets: inherit

  # -------------------------------------------------------------------------
  # JOB 2: OTOMATIS MEMANGGIL WORKER LPUD (Jika xxKSU / SUKISU dipilih)
  # -------------------------------------------------------------------------
  build-lpud-binary:
    if: inputs.ksu_fork == 'xxKSU' || inputs.ksu_fork == 'SUKISU'
    uses: ./.github/workflows/build-lpud.yml
    with:
      ksu_fork: ${{ inputs.ksu_fork }}
      target_arch: 'aarch64-linux-android'
    secrets: inherit
